### PR TITLE
replace add-path with new environment variable

### PR DESCRIPTION
**Pull request by luizirber**
Hello!

I tried using this action in my repo for setting up IPFS, but it failed due to [`add_path` deprecation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). This seems to be the new way (echo the value to an environment variable).

### CODE REVIEW

**Comment by luizirber** [comment]
OK, turns out that [`@actions/core` 1.2.6](https://github.com/actions/toolkit/blob/a5e05630d8e1d89cd75b5a12a972daae8abc6e1a/packages/core/RELEASES.md#126) has the right way, but it was missing running `npm run package` and updating the `dist/index.js` file to actually use it. That's all I did, which turned out to be a massive PR, so I'm happy if this is closed and you regenerate the `dist/index.js` file yourself and commit it to `master` =]

**Comment by ibnesayeed** [comment]
Thanks you so much for the PR. It was on my TODO list since GH announced the deprecation of add path and add environment and moved to using files for them. However, I was too busy wrapping my dissertation up (which I defended last week). At some point I also need to go through all my repos and change their default branch to `main` as that's what GH seem to like going forward.

**Review by ibnesayeed — APPROVED** [review]
LGTM!

**Comment by luizirber** [comment]
> Thanks you so much for the PR. It was on my TODO list since GH announced the deprecation of add path and add environment and moved to using files for them. However, I was too busy wrapping my dissertation up (which I defended last week). At some point I also need to go through all my repos and change their default branch to `main` as that's what GH seem to like going forward.

Congrats on defending! (I finished my PhD in October, so I can relate to your suffering =])

**Comment by ibnesayeed** [comment]
> I finished my PhD in October

Congratulations! I hope you are doing well. What was your research about?

**Comment by luizirber** [comment]
> Congratulations! I hope you are doing well. What was your research about?

Decentralizing indices for public genomic data. You might enjoy [chapter 5](https://github.com/luizirber/phd/blob/5c90c29d5a9177e617bef44a0db4607cdec8987c/thesis/05-decentralized.Rmd), which uses IPFS =]

**Comment by ibnesayeed** [comment]
Very interesting.

**Pull request merged**
